### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by sprlwrksAprilmintacpineda** [polyfillpolyfill/polyfill-service#1740]
I'm trying to use this with our app, but when I installed it, it failed. I tried installing it on an empty project with nothing but the `package.json` in it. Any help or insight would be appreciated. Here's the output

```
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated measured@1.1.0: This package has been renamed to measured-core, all versions of measured have been re-released under measured-core, please update your package and consider updating to the newest version. See https://github.com/yaorg/node-measured for latest updates.
npm WARN deprecated exists-sync@0.0.4: Please replace with usage of fs.existsSync
npm WARN deprecated coffee-script@1.9.0: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

> oniguruma@6.2.1 install /Users/sprlwrks/projects/test/node_modules/oniguruma
> node-gyp rebuild

  CC(target) Release/obj.target/oniguruma/deps/onig/regcomp.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regenc.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regerror.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regexec.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regext.o
  CC(target) Release/obj.target/oniguruma/deps/onig/reggnu.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regparse.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regposerr.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regposix.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regsyntax.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regtrav.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regversion.o
  CC(target) Release/obj.target/oniguruma/deps/onig/st.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/ascii.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/big5.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/cp1251.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_jp.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_kr.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_tw.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/gb18030.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_1.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_2.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_3.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_4.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_5.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_6.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_7.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_8.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_9.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_10.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_11.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_13.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_14.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_15.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_16.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8_r.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/mktable.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/sjis.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/unicode.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_be.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_le.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_be.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_le.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf8.o
  LIBTOOL-STATIC Release/oniguruma.a
  CXX(target) Release/obj.target/onig_scanner/src/onig-result.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-reg-exp.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-scanner.o
../src/onig-scanner.cc:61:23: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
    String::Utf8Value utf8Value(sources->Get(i));
                      ^
/Users/sprlwrks/.node-gyp/10.7.0/include/node/v8.h:2851:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/sprlwrks/.node-gyp/10.7.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
1 warning generated.
  CXX(target) Release/obj.target/onig_scanner/src/onig-scanner-worker.o
../src/onig-scanner-worker.cc:37:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    callback->Call(2, argv);
              ^
../../nan/nan.h:1617:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/onig-scanner-worker.cc:43:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    callback->Call(2, argv);
              ^
../../nan/nan.h:1617:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
2 warnings generated.
  CXX(target) Release/obj.target/onig_scanner/src/onig-searcher.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-string.o
../src/onig-string.cc:26:5: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  : utf8Value(value), utf8_length_(utf8Value.length()) {
    ^
/Users/sprlwrks/.node-gyp/10.7.0/include/node/v8.h:2851:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/sprlwrks/.node-gyp/10.7.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/onig-string.cc:33:19: warning: 'Value' is deprecated [-Wdeprecated-declarations]
    String::Value utf16Value(value);
                  ^
/Users/sprlwrks/.node-gyp/10.7.0/include/node/v8.h:2876:5: note: 'Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version", explicit Value(Local<v8::Value> obj));
    ^
/Users/sprlwrks/.node-gyp/10.7.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/onig-string.cc:30:40: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long')
      [-Wsign-compare]
  hasMultiByteChars = (value->Length() != utf8_length_);
                       ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~
3 warnings generated.
  SOLINK_MODULE(target) Release/onig_scanner.node

> node-zopfli@1.4.0 install /Users/sprlwrks/projects/test/node_modules/shrink-ray/node_modules/node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@10.7.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@10.7.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
  CXX(target) Release/obj.target/zopfli/src/zopfli-binding.o
  CXX(target) Release/obj.target/zopfli/src/zopfli-binding.o
../src/zopfli-binding.cc:136:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    callback->Call(2, argv);
              ^
../../../../nan/nan.h:1617:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/zopfli-binding.cc:136:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    callback->Call(2, argv);
              ^
../../../../nan/nan.h:1617:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
1 warning generated.
1 warning generated.
rm: ./Release/.deps/Release/obj.target/zopfli/src/zopfli-binding.o.d.raw: No such file or directory
make: *** [Release/obj.target/zopfli/src/zopfli-binding.o] Error 1
gyp  CXX(target) Release/obj.target/zopfli/src/png/zopflipng.o
 ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/10.7.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/sprlwrks/projects/test/node_modules/shrink-ray/node_modules/node-zopfli/lib/binding/node-v64-darwin-x64/zopfli.node" "--module_name=zopfli" "--module_path=/Users/sprlwrks/projects/test/node_modules/shrink-ray/node_modules/node-zopfli/lib/binding/node-v64-darwin-x64"
gyp ERR! cwd /Users/sprlwrks/projects/test/node_modules/shrink-ray/node_modules/node-zopfli
gyp ERR! node -v v10.7.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/10.7.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/sprlwrks/projects/test/node_modules/shrink-ray/node_modules/node-zopfli/lib/binding/node-v64-darwin-x64/zopfli.node --module_name=zopfli --module_path=/Users/sprlwrks/projects/test/node_modules/shrink-ray/node_modules/node-zopfli/lib/binding/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/sprlwrks/projects/test/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/10.7.0/bin/node" "/Users/sprlwrks/projects/test/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/sprlwrks/projects/test/node_modules/shrink-ray/node_modules/node-zopfli
node-pre-gyp ERR! node -v v10.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/10.7.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/sprlwrks/projects/test/node_modules/shrink-ray/node_modules/node-zopfli/lib/binding/node-v64-darwin-x64/zopfli.node --module_name=zopfli --module_path=/Users/sprlwrks/projects/test/node_modules/shrink-ray/node_modules/node-zopfli/lib/binding/node-v64-darwin-x64' (1)
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-zopfli@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
../src/png/zopflipng.cc:5:10: fatal error: 'lodepng/lodepng.h' file not found
#include "lodepng/lodepng.h"
         ^~~~~~~~~~~~~~~~~~~

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sprlwrks/.npm/_logs/2018-07-23T03_36_55_240Z-debug.log
1 error generated.
make: *** [Release/obj.target/zopfli/src/png/zopflipng.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/10.7.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/sprlwrks/projects/test/node_modules/shrink-ray/node_modules/node-zopfli/lib/binding/node-v64-darwin-x64/zopfli.node" "--module_name=zopfli" "--module_path=/Users/sprlwrks/projects/test/node_modules/shrink-ray/node_modules/node-zopfli/lib/binding/node-v64-darwin-x64"
gyp ERR! cwd /Users/sprlwrks/projects/test/node_modules/shrink-ray/node_modules/node-zopfli
gyp ERR! node -v v10.7.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
```

Node version: v10.7.0
NPM version: 6.2.0
OS: MacOS 10.13.6

**Comment by JakeChampion** [comment]
This has now been fixed 👍

**Comment by arjun3396** [comment]
> This has now been fixed 👍

but i am still facing in same issue, how to resolve this. thanks in advance.

**Comment by isaldin** [comment]
it wasn't been fixed, guys

Node: v12.10.0
macOS: 10.15.3
yarn: 1.17.3
