### ISSUE TITLE
Version 4.39.1 does not build.

### ISSUE THREAD

**Issue by andersjanmyr** [polyfillpolyfill/polyfill-service#2632]
Build version 4.39.1 does not build. I believe it has something to do with peer dependencies that are not installed correctly.

**Steps to reproduce.**

$ node --version
v12.22.3
$ npm --version
6.14.13

Download release https://github.com/Financial-Times/polyfill-service/archive/refs/tags/v4.39.1.tar.gz
```
tar xzf polyfill-service-4.39.1.tar.gz
cd polyfill-service-4.39.1
npm ci
npm run build
```

Results in:
```
[1067:m2-dev:polyfill-service-4.39.1 169s]
$ npm run build

> polyfill-service@4.28.1 build /Users/anjan9/Downloads/polyfill-service-4.39.1
> run-s clean eleventy build:*


> polyfill-service@4.28.1 clean /Users/anjan9/Downloads/polyfill-service-4.39.1
> rimraf ./dist ./.cache


> polyfill-service@4.28.1 eleventy /Users/anjan9/Downloads/polyfill-service-4.39.1
> eleventy

Writing ./dist/v3/json/library-3.27.4.json from ./src/assets/v3/library.11ty.js.
...
Writing ./dist/v3/json/library-3.103.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/index.html from ./src/assets/v3/index.njk.
Writing ./dist/v3/security-policy/index.html from ./src/assets/v3/security-policy.njk.
Writing ./dist/v3/packages/index.html from ./src/assets/v3/packages.njk.
Writing ./dist/v3/privacy-policy/index.html from ./src/assets/v3/privacy-policy.njk.
Writing ./dist/v3/supported-browsers/index.html from ./src/assets/v3/supported-browsers.njk.
Writing ./dist/v3/report-a-bug/index.html from ./src/assets/v3/report-a-bug.njk.
Writing ./dist/v3/url-builder/index.html from ./src/assets/v3/url-builder.njk.
Writing ./dist/v3/api/index.html from ./src/assets/v3/api.njk.
Writing ./dist/v3/terms/index.html from ./src/assets/v3/terms.njk.
Using pathPrefix: /v3
Copied 9 files / Wrote 37 files in 21.28 seconds (575.1ms each, v0.12.1)

> polyfill-service@4.28.1 build:sass /Users/anjan9/Downloads/polyfill-service-4.39.1
> mkdir -p dist/css && sass src/assets/css/index.scss  --style=compressed --load-path=node_modules --load-path=node_modules/@financial-times | postcss --use autoprefixer --output dist/css/index.css --map

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'postcss'
Require stack:
- /Users/anjan9/Downloads/polyfill-service-4.39.1/node_modules/postcss-cli/index.js
- /Users/anjan9/Downloads/polyfill-service-4.39.1/node_modules/postcss-cli/bin/postcss
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/anjan9/Downloads/polyfill-service-4.39.1/node_modules/postcss-cli/index.js:14:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/anjan9/Downloads/polyfill-service-4.39.1/node_modules/postcss-cli/index.js',
    '/Users/anjan9/Downloads/polyfill-service-4.39.1/node_modules/postcss-cli/bin/postcss'
  ]
}
Error: Can't find stylesheet to import.
  ╷
1 │ @import '@financial-times/o-colors/main';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  o-normalise/main.scss 1:9      @import
  src/assets/css/index.scss 5:9  root stylesheet
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! polyfill-service@4.28.1 build:sass: `mkdir -p dist/css && sass src/assets/css/index.scss  --style=compressed --load-path=node_modules --load-path=node_modules/@financial-times | postcss --use autoprefixer --output dist/css/index.css --map`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the polyfill-service@4.28.1 build:sass script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/anjan9/.npm/_logs/2021-07-16T06_23_42_531Z-debug.log
ERROR: "build:sass" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! polyfill-service@4.28.1 build: `run-s clean eleventy build:*`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the polyfill-service@4.28.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/anjan9/.npm/_logs/2021-07-16T06_23_42_576Z-debug.log
```

**Comment by andersjanmyr** [comment]
I found the problem. I was using the default npm version which is 6 and the peer dependency install requires npm 7.

`npm install -g npm@7` solved it.
