### ISSUE TITLE
>> Error: No polyfill sources found.  Run `grunt buildsources` to build them

### ISSUE THREAD

**Issue by monolithed** [polyfillpolyfill/polyfill-service#339]
```
Loading "polyfill-service.js" tasks...ERROR
>> Error: No polyfill sources found.  Run `grunt buildsources` to build them
Warning: Task "polyfill-service" failed. Use --force to continue.

Aborted due to warnings.
```

1.4.0 ? :game_die:

**Comment by triblondon** [comment]
Could you clarify what error you're reporting here?  Did the `buildsources` task not work?

**Comment by monolithed** [comment]
```
npm install polyfill-service
```

``` js
// test.js
var service = require('polyfill-service');

service.getPolyfillString({
    uaString: 'MSIE 7.0',
    features: {
        'Math.acosh': {
            flags: ['always', 'gated']
        }
    }
});
```

```
node test.js
```

```
➜ node test.js 
/node_modules/polyfill-service/lib/sources.js:11
    throw Error("No polyfill sources found.  Run `grunt buildsources` to build th
          ^
Error: No polyfill sources found.  Run `grunt buildsources` to build them
    at Error (native)
    at Object.<anonymous> (/node_modules/polyfill-service/lib/sources.js:11:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/node_modules/polyfill-service/lib/index.js:5:18)
    at Module._compile (module.js:460:26)
```

I don't want to do something like:

```
npm install polyfill-service
cd node_modules/polyfill-service
npm install 
grunt buildsources
```

> Did the buildsources task not work?

```
➜ cd node_modules/polyfill-service
➜ grunt buildsources

grunt-cli: The grunt command line interface. (v0.1.13)
```

```
➜ npm install # surprise #341
```

Please see my another issue https://github.com/Financial-Times/polyfill-service/issues/341

**Comment by triblondon** [comment]
The package.json contains:

```
    "prepublish": "grunt build",
```

So the sources should be built as part of the npm package.  I'm afraid I'm a bit out of my depth here.

**Comment by monolithed** [comment]
You'd install yourself

**Comment by triblondon** [comment]
I've discovered that when publishing to npm, npm ignores everything in .gitignore by default, which includes the built polyfills.  I've created an npmignore that should fix it.

https://github.com/Financial-Times/polyfill-service/commit/365eb6000dda40dd8dc5398f02fb837e6a3b0730
