### ISSUE TITLE
One-click deploy button doesn't work

### ISSUE THREAD

**Issue by callumlocke** [polyfillpolyfill/polyfill-service#355]
I just tried the one-click deploy, but when I open the homepage in my browser, it just shows me the standard heroku 500 error.

I looked in the heroku logs:

```
2015-03-19T20:14:04.170229+00:00 heroku[web.1]: Starting process with command `node service/index.js`
2015-03-19T20:14:05.868259+00:00 app[web.1]: Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
2015-03-19T20:14:05.868326+00:00 app[web.1]: Recommending WEB_CONCURRENCY=1
2015-03-19T20:14:06.063374+00:00 app[web.1]: /app/lib/sources.js:11
2015-03-19T20:14:06.063380+00:00 app[web.1]:    throw Error("No polyfill sources found.  Run `grunt buildsources` to build th
2015-03-19T20:14:06.063382+00:00 app[web.1]:          ^
2015-03-19T20:14:06.063384+00:00 app[web.1]: Error: No polyfill sources found.  Run `grunt buildsources` to build them
2015-03-19T20:14:06.063385+00:00 app[web.1]:     at Error (native)
2015-03-19T20:14:06.063387+00:00 app[web.1]:     at Object.<anonymous> (/app/lib/sources.js:11:8)
2015-03-19T20:14:06.063389+00:00 app[web.1]:     at Module._compile (module.js:460:26)
2015-03-19T20:14:06.063391+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:478:10)
2015-03-19T20:14:06.063392+00:00 app[web.1]:     at Module.load (module.js:355:32)
2015-03-19T20:14:06.063394+00:00 app[web.1]:     at Function.Module._load (module.js:310:12)
2015-03-19T20:14:06.063396+00:00 app[web.1]:     at Module.require (module.js:365:17)
2015-03-19T20:14:06.063397+00:00 app[web.1]:     at require (module.js:384:17)
2015-03-19T20:14:06.063399+00:00 app[web.1]:     at Object.<anonymous> (/app/lib/index.js:5:18)
2015-03-19T20:14:06.063400+00:00 app[web.1]:     at Module._compile (module.js:460:26)
2015-03-19T20:14:06.876645+00:00 heroku[web.1]: State changed from starting to crashed
2015-03-19T20:14:06.877551+00:00 heroku[web.1]: State changed from crashed to starting
2015-03-19T20:14:06.863276+00:00 heroku[web.1]: Process exited with status 1
```

**Comment by monolithed** [comment]
https://github.com/Financial-Times/polyfill-service/issues/339

**Comment by triblondon** [comment]
Thanks Callum.  I'm not convinced that button is really that useful, but it points to a bigger issue of the service not working when installed from npm.  Fixed, I hope, in https://github.com/Financial-Times/polyfill-service/commit/365eb6000dda40dd8dc5398f02fb837e6a3b0730.
